#!/usr/bin/env bash
set -Eeu -o pipefail

# """
# koopa piped install script.
# Updated 2020-02-15.
#
# This downloads a copy of the latest stable release into a temporary directory.
# """

release="rolling"

if [[ "$#" -gt 0 ]]
then
    pos=()
    while (("$#"))
    do
        case "$1" in
        --release=*)
            release="${1#*=}"
            shift 1
            ;;
        --release)
            release="$2"
            shift 2
            ;;
        *)
            pos+=("$1")
            shift 1
            ;;
        esac
    done
    if [[ "${#pos[@]}" -gt 0 ]]
    then
        set -- "${pos[@]}"
    fi
fi

repo="acidgenomics/koopa"

if [[ "$release" == "rolling" ]]
then
    echo "Installing koopa."
    echo "Using rolling release from master branch."
    echo "This can be updated using 'koopa update'."
    git_url="https://github.com/${repo}.git"
    # Alternatively, here's how to get master branch tarball:
    # > tarball_url="https://github.com/${repo}/tarball/master"
else
    # Note that use of 'api.github.com' here returns JSON instead of HTML.
    json_url="https://api.github.com/repos/${repo}/releases/${release}"
    json="$(curl -s "$json_url")"
    tarball_url="$( \
        echo "$json" \
            | grep '"tarball_url":' \
            | cut -d '"' -f 4 \
    )"
    tag_name="$( \
        echo "$json" \
            | grep '"tag_name":' \
            | cut -d '"' -f 4 \
    )"
    echo "Installing koopa ${tag_name}."
    echo "This is a stable release that cannot be updated."
fi

tmp_dir="$(mktemp -d)"
# > echo "tmpdir: '${tmp_dir}'."

(
    cd "$tmp_dir" || exit 1
    if [[ "$release" == "rolling" ]]
    then
        git clone --quiet --recursive "$git_url" koopa
        cd koopa || exit 1
    else
        file="koopa.tar.gz"
        curl \
            --location \
            --output "$file" \
            --silent \
            "$tarball_url"
        tar -xzf "$file"
        cd acidgenomics-koopa-* || exit 1
    fi
    ./install "$@"
)

rm -fr "$tmp_dir"
