#!/usr/bin/env bash
set -Eeu -o pipefail

# """
# koopa piped install script.
# Updated 2020-01-21.
#
# See also:
# - https://unix.stackexchange.com/questions/180383
# """

tmpdir="${TMPDIR:-/tmp}"
install="${tmpdir}/install-koopa.sh"
curl -o "$install" "https://raw.githubusercontent.com/acidgenomics/koopa/master/install"
chmod +x "$install"
"${install}" "$@"
rm "$install"
